// Code generated by counterfeiter. DO NOT EDIT.
package portsfakes

import (
	"context"
	"sync"

	"github.com/vinaycharlie01/shroute/backend/internal/application/ports"
	"github.com/vinaycharlie01/shroute/backend/internal/domain/audit"
)

type FakeAuditRepository struct {
	AppendStub        func(context.Context, audit.Entry) (audit.Entry, error)
	appendMutex       sync.RWMutex
	appendArgsForCall []struct {
		arg1 context.Context
		arg2 audit.Entry
	}
	appendReturns struct {
		result1 audit.Entry
		result2 error
	}
	appendReturnsOnCall map[int]struct {
		result1 audit.Entry
		result2 error
	}
	ListStub        func(context.Context, int) ([]audit.Entry, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	listReturns struct {
		result1 []audit.Entry
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []audit.Entry
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuditRepository) Append(arg1 context.Context, arg2 audit.Entry) (audit.Entry, error) {
	fake.appendMutex.Lock()
	ret, specificReturn := fake.appendReturnsOnCall[len(fake.appendArgsForCall)]
	fake.appendArgsForCall = append(fake.appendArgsForCall, struct {
		arg1 context.Context
		arg2 audit.Entry
	}{arg1, arg2})
	stub := fake.AppendStub
	fakeReturns := fake.appendReturns
	fake.recordInvocation("Append", []interface{}{arg1, arg2})
	fake.appendMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuditRepository) AppendCallCount() int {
	fake.appendMutex.RLock()
	defer fake.appendMutex.RUnlock()
	return len(fake.appendArgsForCall)
}

func (fake *FakeAuditRepository) AppendCalls(stub func(context.Context, audit.Entry) (audit.Entry, error)) {
	fake.appendMutex.Lock()
	defer fake.appendMutex.Unlock()
	fake.AppendStub = stub
}

func (fake *FakeAuditRepository) AppendArgsForCall(i int) (context.Context, audit.Entry) {
	fake.appendMutex.RLock()
	defer fake.appendMutex.RUnlock()
	argsForCall := fake.appendArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuditRepository) AppendReturns(result1 audit.Entry, result2 error) {
	fake.appendMutex.Lock()
	defer fake.appendMutex.Unlock()
	fake.AppendStub = nil
	fake.appendReturns = struct {
		result1 audit.Entry
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditRepository) AppendReturnsOnCall(i int, result1 audit.Entry, result2 error) {
	fake.appendMutex.Lock()
	defer fake.appendMutex.Unlock()
	fake.AppendStub = nil
	if fake.appendReturnsOnCall == nil {
		fake.appendReturnsOnCall = make(map[int]struct {
			result1 audit.Entry
			result2 error
		})
	}
	fake.appendReturnsOnCall[i] = struct {
		result1 audit.Entry
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditRepository) List(arg1 context.Context, arg2 int) ([]audit.Entry, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1, arg2})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuditRepository) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeAuditRepository) ListCalls(stub func(context.Context, int) ([]audit.Entry, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeAuditRepository) ListArgsForCall(i int) (context.Context, int) {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuditRepository) ListReturns(result1 []audit.Entry, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []audit.Entry
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditRepository) ListReturnsOnCall(i int, result1 []audit.Entry, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []audit.Entry
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []audit.Entry
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuditRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ports.AuditRepository = new(FakeAuditRepository)
