// Code generated by counterfeiter. DO NOT EDIT.
package portsfakes

import (
	"context"
	"sync"

	"github.com/vinaycharlie01/shroute/backend/internal/application/ports"
	"github.com/vinaycharlie01/shroute/backend/internal/domain/cache"
)

type FakeCacheStore struct {
	FlushStub        func(context.Context, string) error
	flushMutex       sync.RWMutex
	flushArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	flushReturns struct {
		result1 error
	}
	flushReturnsOnCall map[int]struct {
		result1 error
	}
	ListStub        func(context.Context, string, int) ([]cache.Entry, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	listReturns struct {
		result1 []cache.Entry
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []cache.Entry
		result2 error
	}
	StatsStub        func(context.Context) (cache.Stats, error)
	statsMutex       sync.RWMutex
	statsArgsForCall []struct {
		arg1 context.Context
	}
	statsReturns struct {
		result1 cache.Stats
		result2 error
	}
	statsReturnsOnCall map[int]struct {
		result1 cache.Stats
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCacheStore) Flush(arg1 context.Context, arg2 string) error {
	fake.flushMutex.Lock()
	ret, specificReturn := fake.flushReturnsOnCall[len(fake.flushArgsForCall)]
	fake.flushArgsForCall = append(fake.flushArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FlushStub
	fakeReturns := fake.flushReturns
	fake.recordInvocation("Flush", []interface{}{arg1, arg2})
	fake.flushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCacheStore) FlushCallCount() int {
	fake.flushMutex.RLock()
	defer fake.flushMutex.RUnlock()
	return len(fake.flushArgsForCall)
}

func (fake *FakeCacheStore) FlushCalls(stub func(context.Context, string) error) {
	fake.flushMutex.Lock()
	defer fake.flushMutex.Unlock()
	fake.FlushStub = stub
}

func (fake *FakeCacheStore) FlushArgsForCall(i int) (context.Context, string) {
	fake.flushMutex.RLock()
	defer fake.flushMutex.RUnlock()
	argsForCall := fake.flushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCacheStore) FlushReturns(result1 error) {
	fake.flushMutex.Lock()
	defer fake.flushMutex.Unlock()
	fake.FlushStub = nil
	fake.flushReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacheStore) FlushReturnsOnCall(i int, result1 error) {
	fake.flushMutex.Lock()
	defer fake.flushMutex.Unlock()
	fake.FlushStub = nil
	if fake.flushReturnsOnCall == nil {
		fake.flushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.flushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCacheStore) List(arg1 context.Context, arg2 string, arg3 int) ([]cache.Entry, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1, arg2, arg3})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCacheStore) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeCacheStore) ListCalls(stub func(context.Context, string, int) ([]cache.Entry, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeCacheStore) ListArgsForCall(i int) (context.Context, string, int) {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCacheStore) ListReturns(result1 []cache.Entry, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []cache.Entry
		result2 error
	}{result1, result2}
}

func (fake *FakeCacheStore) ListReturnsOnCall(i int, result1 []cache.Entry, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []cache.Entry
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []cache.Entry
		result2 error
	}{result1, result2}
}

func (fake *FakeCacheStore) Stats(arg1 context.Context) (cache.Stats, error) {
	fake.statsMutex.Lock()
	ret, specificReturn := fake.statsReturnsOnCall[len(fake.statsArgsForCall)]
	fake.statsArgsForCall = append(fake.statsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.StatsStub
	fakeReturns := fake.statsReturns
	fake.recordInvocation("Stats", []interface{}{arg1})
	fake.statsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCacheStore) StatsCallCount() int {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	return len(fake.statsArgsForCall)
}

func (fake *FakeCacheStore) StatsCalls(stub func(context.Context) (cache.Stats, error)) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = stub
}

func (fake *FakeCacheStore) StatsArgsForCall(i int) context.Context {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	argsForCall := fake.statsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCacheStore) StatsReturns(result1 cache.Stats, result2 error) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	fake.statsReturns = struct {
		result1 cache.Stats
		result2 error
	}{result1, result2}
}

func (fake *FakeCacheStore) StatsReturnsOnCall(i int, result1 cache.Stats, result2 error) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	if fake.statsReturnsOnCall == nil {
		fake.statsReturnsOnCall = make(map[int]struct {
			result1 cache.Stats
			result2 error
		})
	}
	fake.statsReturnsOnCall[i] = struct {
		result1 cache.Stats
		result2 error
	}{result1, result2}
}

func (fake *FakeCacheStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCacheStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ports.CacheStore = new(FakeCacheStore)
